# Generated by Django 5.1.2 on 2024-11-01 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_post_post_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='post',
            new_name='Note',
        ),
    ]
